<?php

namespace CT\CoreBundle\Repository;

/**
 * paymentTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paymentTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
