<?php

namespace CT\CoreBundle\Repository;

/**
 * PlexPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlexPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
