<?php

namespace CT\CoreBundle\Repository;

/**
 * ShiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByRange($startDate, $endDate)
    {

        dump($endDate);
        $qb = $this
            ->createQueryBuilder('a')
            ->andWhere('a.startsAt >= :startDate')
            ->setParameter('startDate', $startDate)
            ->andWhere('a.endsAt <= :endDate')
            ->setParameter('endDate', $endDate)
            ->addSelect('a')
            ->leftJoin('a.applications', 'applications')
            ->addSelect('applications')
            ->leftJoin('applications.user', 'user')
            ->addSelect('user')

        ;

        return $qb
            ->getQuery()
            ->getArrayResult()
            ;
    }

    public function findByRangeAndDepartment($startDate, $endDate, $department)
    {

        dump($endDate);
        $qb = $this
            ->createQueryBuilder('a')
            ->andWhere('a.startsAt >= :startDate')
            ->setParameter('startDate', $startDate)
            ->andWhere('a.endsAt <= :endDate')
            ->setParameter('endDate', $endDate)
            ->addSelect('a')
            ->leftJoin('a.applications', 'applications')
            ->addSelect('applications')
            ->leftJoin('applications.user', 'user')
            ->addSelect('user')
            ->leftJoin('a.department', 'department')
            ->andWhere('department.id LIKE :department')
            ->setParameter('department', $department)
            ->addSelect("department")
            ->leftJoin('department.location', 'location')
            ->addSelect("location")
        ;

        return $qb
            ->getQuery()
            ->getArrayResult()
            ;
    }
}
